# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Reaktivity

# Description will appear in your document head meta (for
# Google search results) and in your feed.xml site description.
description: > # this means to ignore newlines until "baseurl:"
  Build shared memory microservices on any platform in any language

baseurl: "" # the subpath of your site, e.g. /blog
url: ""     # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: jekyll-theme-slate
markdown: kramdown
highlighter: rouge
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

# Development settings
livereload: true   # Browser will automatically refresh when a file is saved
